### ISSUE TITLE
jspm: Speed up typescript compile

### ISSUE THREAD

**Issue by jp7677** [jp7677/hellocoreclr#8]
Using
```
var tsResult = gulp.src([paths.src + '**/*.ts', paths.test + '**/*.ts', '!' + paths.jspmPackages], { base: '.' })
```
instead of
```
var tsResult = tsProject.src()
```
We can revert that eventually with a new gulp-typescript version, see https://github.com/ivogabe/gulp-typescript/issues/326

**Comment by jp7677** [comment]
Resolved with https://github.com/jp7677/hellocoreclr/commit/acce440cf29fbec8fa504983dde32831d25d363f.

**Comment by ivogabe** [comment]
The performance issue should be solved with the latest release of gulp-typescript.

**Comment by jp7677** [comment]
@ivogabe Cool, thanks a lot for letting me know!
